---
strategy:
  type: copy
  pair: ETHUSD
  target:
    driver: rubykube
    host: http://stage.tradence.io
    name: John
    key: changeme
    secret: changeme
  sources:
  - driver: bitfinex
    name: Joe
    key: changeme
    secret: changeme

