version: '3.6'

services:
  proxy:
    image: traefik:1.7.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - stage.tradence.io
          - peatio.tradence.io
          - ws.ranger.tradence.io
#          - eth.
          - tower.tradence.io
          - monitor.tradence.io
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.tradence.io'
      traefik.port: 8080
